### ISSUE TITLE
No values being calaculated - AF or AC

### ISSUE THREAD

**Issue by Jambo1998** [jamesware/alleleFrequencyApp#3]
I was trying to use the calculator / app for the first time, but I can't get it to calculate any values.
Is there any problem or am I doing something wrong ?

**Comment by jamesware** [comment]
Hi,
In what context are you using it?  Have you downloaded source code from here and deployed yourself, or as you using the web implementation that we have provided?
It is working fine for me at http://cardiodb.org/allelefrequencyapp/

**Comment by Jambo1998** [comment]
Hi,

           I am trying to use it through


http://cardiodb.org/allelefrequencyapp/?


But can't see any values /scores when I change the prevalence or genetic heterogenity etc


?

________________________________

**Comment by jamesware** [comment]
Not sure - this is working here - tested on different browsers at that URL, and performing as expected...
Is the app loading initially?  Is it just a (very long) transmission lag in updating values after the parameters have changed?  I'll speak to our Sys Admin about checking resources this end - please do let me know if this persists...

**Comment by Jambo1998** [comment]
I have attached some screenshots where I have changed the parameters but there are no values given.? I hope they help


when I go to http://cardiodb.org/allelefrequencyapp/   the screen 'greys out' after about 3 seconds. Is this normal ? could this indicate any loading problems ?



Stephen Tennant
Principal Clinical Scientist
Department of Medical Genetics
Aberdeen

http://www.nhsgrampian.org/medicalgenetics<https://web.nhs.net/owa/redir.aspx?C=O5zqckFu9k2YCwrZpA0IvWwKdQ1rGNBIS-OuNt2gmGECF8POPUW3D3pMZ_51mJRqsP44SwAKpHU.&URL=http%3a%2f%2fwww.nhsgrampian.org%2fmedicalgenetics>
________________________________

**Comment by mianasbat** [comment]
Hi Stephen Tennant, 
Jamesware assigned me to this issue. 
I am not able to see the screenshot but the testing suggests that your organisation is using proxy server. Shiny server doesn't like proxying of its data because it communicates interactively. To confirm if this is the case, please disable wifi on your mobile (if enabled) and browse to the website http://cardiodb.org/allelefrequencyapp/ using your mobile data plan. Everything should work fine. 

If proxy is the problem, you can ask your Sys Admin to disable caching (using proxy) for http://cardiodb.org or on your computer disable proxy.
